### ISSUE TITLE
"http://localhost" doesn't work and "localhost" does

### ISSUE THREAD

**Issue by rfustino** [algorand/java-algorand-sdk#152]
The error occurs in v 1.4.0 , on the line:

indexerClientInstance.lookupBlock(block).execute()

working sample code works.. To replicate error, change the value of 
final String INDEXER_API_ADDR = "localhost";
to
final String INDEXER_API_ADDR = "http://localhost";

[BlockInfo.java.zip](https://github.com/algorand/java-algorand-sdk/files/4754788/BlockInfo.java.zip)

**Comment by winder** [comment]
@rfustino this is fixed in 1.4.2, thanks for the suggestion. You can now specify https as well.
