### ISSUE TITLE
Organize Project With Modules

### ISSUE THREAD

**Issue by winder** [algorand/java-algorand-sdk#159]
This project could be cleanly separated into modules to split out the generated code, code generator, and better integrate the example project:
* SDK - Build & Deploy configuration, depends on **Base**, **REST Client** and **Builders**.
* Base - Almost all of the interesting code could be here. Crypto, Encoding utils, Tests, etc.
* REST Client - The generated code. Because the generated code uses "real" types, this module would depend on **Base**.
* Builders - Split into its own module to avoid a circular dependency. Depends on **Base** for Transaction objects and **REST Client** for Clients and TransactionParameterResponse type.
* Example - This is a standalone project that pulls in all of the other modules.
* Generator - This should probably be split into its own repository at some point. It will likely depend on the SDK at some point in order to generate test code.

**Comment by algorotem** [comment]
Iceboxed until v1 deprecation
