### ISSUE TITLE
Add default Content-Type on RawTransaction

### ISSUE THREAD

**Issue by fxgamundi** [algorand/java-algorand-sdk#198]
When sending a raw transaction with v2 client, the content of the body is `application/x-binary`, but the content-type header indicating this is not added by default.
This header is added by default in the Go, JS and Python SDKs, and was added by default in the [v1 client of this SDK](https://github.com/algorand/java-algorand-sdk/blob/develop/src/main/java/com/algorand/algosdk/algod/client/api/DefaultApi.java#L1243).

**Comment by ian-algorand** [comment]
Relatively easy win, we can definitely do this

**Comment by urajbhandari** [comment]
Hi I want to understand more about this issue. When do we need to set application/x-binary header. I saw an example about PureStake where it is used: https://developer.algorand.org/tutorials/creating-java-transaction-purestake-api/#5-create-and-sign-transaction. 

Do we need that header only when we use PureStake?

**Comment by urajbhandari** [comment]
Python PureStake tutorial is much easier/elegant than Java (see https://developer.algorand.org/tutorials/creating-python-transaction-purestake-api/).  In Python, they just set the token header only once. Is this issue about making Java API more user friendly similar to the Python API?

**Comment by winder** [comment]
@urajbhandari you can use this constructor to set the token header once: https://github.com/algorand/java-algorand-sdk/pull/197

Regarding what this issue is, it refers to the content-type header. It isn't set when submitting a transaction. For a simple solution, we could put something [in the base query](https://github.com/algorand/java-algorand-sdk/blob/develop/src/main/java/com/algorand/algosdk/v2/client/common/Query.java#L27) that sets `application/x-binary` if there is a body.

In the future it might require an extra argument for the content-type in `baseExecute`, but that would require changing the client code generator to set the new field.

**Comment by FranckRo** [comment]
Hello @winder,

I'm also interested by fixing some issues including this one (thanks for all documentation/tutorials about Algorand).

For this one, I understood that the header Content-Type has to be added to RawTransaction only. If I understand well your last comment (the simple solution by putting header in base query) so Content-type will be added as soon as a body exists but for all transaction type. What is the solution to implement?

Thanks for your response

**Comment by winder** [comment]
@FranckRo I was mistaken. Looking at [daemon/algod/api/algod.oas2.json](https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas2.json#L1142) I see that */v2/teal/dryrun* accepts `application/json` and `application/msgpack`.

This means the second solution I mentioned which [updates the code generator](https://github.com/algorand/generator/blob/master/src/main/java/com/algorand/sdkutils/listeners/JavaGenerator.java) is needed, it would set `application/x-binary` or `application/msgpack`.

This probably isn't a very good first.

**Comment by urajbhandari** [comment]
@winder thanks for the explanation.

One way of implementing would be to add a setter method for content type in AlgodClient or its super class Client.  The setter method can be called after constructing AlgodClient. Client's executeCall() method can then access the content type and set in the header. If no content type is set, then we can default to a default value. It looks like the default for Accept is "application/json" and for Content-Type is "application-x-binary"

Alternatively we could create additional constructor(s) with the last param as a Map to pass headers. We can then filter the keys and use Accept and Content-Type values.
