### ISSUE TITLE
Wrong decoding of base32 String to byte[]

### ISSUE THREAD

**Issue by rajathchain** [algorand/java-algorand-sdk#209]
The `decodeFromBase32StripPad((String bytes)` function in `com.algorand.algosdk.util.Encoder` seems to have a bug.

Example: 
If you switch out `3DV5VXT3QFRPVRTZTWP7PSGJN37BXJNXQWAFFW34OJWIZ2UOINQQ` with `B3R46T7Z3JYHSZUMDKVQQKBYLJKWLJ36FQ5OJ3FFSWFXNXJ5HURQ` which is a valid mainnet transaction, your test case in the `TestEncoder` class fails. This has to got to do with how the `=` pad stripping is being handled in the function.

`TestEncoder` Output:
```
org.opentest4j.AssertionFailedError: 
Expecting:
 <"B3R46T7Z3JYHSZUMDKVQQKBYLJKWLJ36FQ5OJ3FFSWFXNXI">
to be equal to:
 <"B3R46T7Z3JYHSZUMDKVQQKBYLJKWLJ36FQ5OJ3FFSWFXNXJ5HURQ">
but was not.
Expected :"B3R46T7Z3JYHSZUMDKVQQKBYLJKWLJ36FQ5OJ3FFSWFXNXJ5HURQ"
Actual   :"B3R46T7Z3JYHSZUMDKVQQKBYLJKWLJ36FQ5OJ3FFSWFXNXI"
```

Here's what I think the fix should look like:
```
public static byte[] decodeFromBase32StripPad(String base32Str) {
        Base32 codec = new Base32((byte)BASE32_PAD_CHAR);
        // strip padding
        int i = 0;
        for (; i < base32Str.length(); i++) {
            if (base32Str.charAt(i) == BASE32_PAD_CHAR) {
                break;
            }
        }
        byte[] paddedStr =  codec.decode(base32Str.substring(0, i));
        return Arrays.copyOf(paddedStr, paddedStr.length);
    }
```

**Comment by winder** [comment]
@rajathchain thank you for the detailed bug report, we'll have a fix for this in the next release!
