### ISSUE TITLE
how to change default kmd config

### ISSUE THREAD

**Issue by bylun** [algorand/java-algorand-sdk#247]
kmd started , default ip and port 127.0.0.1 7833,   how to modify this default config ?

**Comment by winder** [comment]
There is a small example in the README:
```
        KmdClient kmdClient = new KmdClient();
        kmdClient.setBasePath("http://localhost:4002");
        kmdClient.setApiKey(token);
        kmd = new KmdApi(kmdClient);
```

**Comment by bylun** [comment]
I'm glad to receive your reply.  I solved it on the day of the question.

My method :   
in the kmd_config file, add param : "address": "172.28.26.74:7833"

2021-09-09 

weinan2087 



发件人：Will Winder ***@***.***>
发送时间：2021-09-08 22:23
主题：Re: [algorand/java-algorand-sdk] how to change default kmd config (#247)
***@***.***>
***@***.******@***.***>

There is a small example in the README:
        KmdClient kmdClient = new KmdClient();
        kmdClient.setBasePath("http://localhost:4002");
        kmdClient.setApiKey(token);
        kmd = new KmdApi(kmdClient);

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
