### ISSUE TITLE
Add ParticipationUpdates to BlockHeader

### ISSUE THREAD

**Issue by algochoi** [algorand/java-algorand-sdk#310]
## Problem

There was a [PR in the Go SDK](https://github.com/algorand/go-algorand-sdk/pull/306) that added `ParticipationUpdates` to the `BlockHeader` type, and we should do something similar for the [Java SDK](https://github.com/algorand/go-algorand-sdk/pull/306). 

## Solution

Add field to header, plus any relevant tests.

**Comment by michaeldiamant** [comment]
As part of the effort, it's worth considering a change analogous to https://github.com/algorand/go-algorand-sdk/pull/307/.  Making the analogous change:
* Brings java-algorand-sdk into conformance with other SDK behavior.
* Avoids causing errors when a new BlockHeader is missed in java-algorand-sdk.  

A process change to catch missed BlockHeaders feels prudent though out-of-scope.

**Comment by michaeldiamant** [comment]
Closing - Per discussion with @winder and @ahangsu, the Java SDK is _not_ subject to the listed shortcomings.

The Java SDK uses a `Map` to represent the blocker header response:  https://github.com/algorand/java-algorand-sdk/blob/ccedd878e3ac961579444d8e6a2c99df89e87d7f/src/main/java/com/algorand/algosdk/v2/client/model/BlockResponse.java#L18.   Unlike go-algorand-sdk, the implementation tolerates unknown fields.
