### ISSUE TITLE
Boolean is not converting correctly in ATC method call in Gson parsing

### ISSUE THREAD

**Issue by michaeltchuang** [algorand/java-algorand-sdk#509]
### Subject of the issue

This is the contract I'm targeting against: https://github.com/algorand-devrel/coin-flipper/blob/master/contracts/artifacts/contract.json

`Boolean` is not converting correctly in ATC method call.  Kotlin doesn't have Java `boolean` type, only `Boolean`

### Your environment

```
suspend fun createTransactionWithSigner(account: Account, appId: Long, amount: Int) : TransactionWithSigner {
        return withContext(Dispatchers.IO) {
            // Get suggested params from client
            val rsp: Response<TransactionParametersResponse> = client.TransactionParams().execute()
            val sp: TransactionParametersResponse = rsp.body()

            // Create a transaction
            val ptxn = PaymentTransactionBuilder.Builder()
                .suggestedParams(sp)
                .amount(amount)
                .sender(account.address)
                .receiver(Address.forApplication(appId))
                .build()

            // Construct TransactionWithSigner
            val tws = TransactionWithSigner(ptxn, account.transactionSigner)
            tws
        }
    }

suspend fun appFlipCoin(account: Account, appId: Long, contractStr: String, amount: Int, isHeads: Boolean) : AtomicTransactionComposer.ExecuteResult {
        return withContext(Dispatchers.IO) {
            val contract: Contract = Gson().fromJson(contractStr, Contract::class.java)

            val rsp = client.TransactionParams().execute()
            val tsp: TransactionParametersResponse = rsp.body()
            val tws = createTransactionWithSigner(account, appId, amount)
            val method_args = listOf(tws, isHeads)

            // create methodCallParams by builder (or create by constructor) for add method
            val mctb = MethodCallTransactionBuilder.Builder()
            mctb.applicationId(appId)
            mctb.sender(account.address.toString())
            mctb.signer(account.transactionSigner)
            mctb.suggestedParams(tsp)
            mctb.method(getMethodByName("flip_coin", contract))
            mctb.methodArguments(method_args)
            mctb.onComplete(Transaction.OnCompletion.OptInOC)

            val atc = AtomicTransactionComposer()
            atc.addTransaction(tws);
            atc.addMethodCall(mctb.build())

            val res = atc.execute(client, 100)

            res.methodResults.forEach(Consumer<ReturnValue> { methodResult: ReturnValue? ->
                Log.d(TAG,
                    methodResult.toString()
                )
            })

            Log.d(TAG, "flip coin call success for app-id: $appId")
            res
        }
    }

// Utility function to return an ABIMethod by its name
    @Throws(java.lang.Exception::class)
    fun getMethodByName(name: String, contract: Contract): Method? {
        val m: Optional<Method> = contract.methods.stream().filter { mt ->
            mt.name.equals(
                name
            )
        }.findFirst()
        return m.orElseThrow { java.lang.Exception("Method undefined: $name") }
    }
```

### Steps to reproduce

1. Use Algorand Java SDK `2.0.0` in an android project like: https://github.com/michaeltchuang/algorand-devrel-coin-flipper/tree/feat/android-version 
2. Call my appFlipCoin function (by restoring a hardcoded wallet -> play game -> pick a coin in UI)...or I pasted relevant code snippet into issue above.
3. Add Kotlin `Boolean` to params like `val method_args = listOf(tws, isHeads)`
4. Algorand Java SDK can't convert `bool` correctly on `atc.addMethodCall(mctb.build())` call

### Expected behaviour

- Kotlin Boolean should be accepted as an ATC method param

### Actual behaviour
- Throws this error because it doesn't recognize `Boolean` type

```
java.lang.IllegalArgumentException: error: the type of method argument is a transaction-type, but no transaction-with-signer provided
        at com.algorand.algosdk.transaction.MethodCallParams.createTransactions(MethodCallParams.java:172)
        at com.algorand.algosdk.transaction.AtomicTransactionComposer.addMethodCall(AtomicTransactionComposer.java:109)
```

**Comment by winder** [comment]
It's been a while since I've used Kotlin, so I can't give a specific recommendation here.

This is a java library, as you're probably aware you sometimes need to jump through hoops to get it working with Kotlin.

Would this help?
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/java-object-type.html

**Comment by michaeltchuang** [comment]
so I did try `val method_args = listOf(tws, isHeads::class.java)` but I believe all that does is convert Kotlin `Boolean` to Java `Boolean` and not Java `boolean`, so no difference and same error.  There is no `boolean` type in Kotlin.  I also tried parameter as `1` which made it recognize as `Integer` and "True" as `String`.

I was thinking maybe `ABIType` class could accept `Boolean` and convert it to `boolean` if not null?  https://github.com/algorand/java-algorand-sdk/blob/develop/src/main/java/com/algorand/algosdk/abi/ABIType.java#L75

if you have other suggestions fro me to try, feel to throw them out while I continue looking online for potential fix.

**Comment by barnjamin** [comment]
It does look like its properly encoding a Boolean value and a tuple of Booleans

![image](https://user-images.githubusercontent.com/520236/222190523-97e64950-c5ab-405e-9f57-fbc95b4875ff.png)


Why does the error you got complaining about TransactionWithSigner make you think its related to bools?

**Comment by michaeltchuang** [comment]
This is what I'm seeing from `MethodCallParams.java` where error is being thrown.  In the `for` loop (line 137 of file), the first parameter (`TransactionWithSigner` type) parses as I expect, but for the second parameter (`Boolean` type), it throws an exception and here is the debug information through the loop.

The first `if` statement (line 140) deals with `TransactionWithSigner` so it's skipped, and this is the second one (line 148 of file) which it also skips.

<img width="990" alt="Screenshot 2023-02-28 at 10 53 28 AM" src="https://user-images.githubusercontent.com/834255/222204961-da9f56a6-d8ee-4d05-a96b-12542d9188a3.png">

The third one (line 168 of file) looks at `argT.parsedType`, but it is `null` for Boolean, which make it skip this case too.  Here is the breakpoint.

<img width="1050" alt="Screenshot 2023-02-28 at 10 54 15 AM" src="https://user-images.githubusercontent.com/834255/222202593-df5f40b3-40dd-4047-abf2-0ddbeabaf2b8.png">

Here is the `else` statement (line 171 of file) that throws the error below it

<img width="1203" alt="Screenshot 2023-02-28 at 10 54 36 AM" src="https://user-images.githubusercontent.com/834255/222202438-7c461166-90e1-421d-9687-64ad87dec7d8.png">

This is why I think it has something to do with my parameter `Boolean`.  I can't seem to pass this `for` loop without an exception thrown.  I did list out the `contract.json` file I'm targeting and how I am passing the Boolean value in ATC method call (in original post) in case you wanted to see how I am calling the Java SDK.

**Comment by barnjamin** [comment]
1) thats a terrible error message 
2) this seems to work for me 🤔 
![image](https://user-images.githubusercontent.com/520236/222220073-f7ea4e02-6fe6-4143-a138-aed3c8488bcd.png)

**Comment by barnjamin** [comment]
created https://github.com/algorand/java-algorand-sdk/pull/511 for the err msg thing so we don't forget to fix that but its untested

**Comment by michaeltchuang** [comment]
can you convert your test code to Kotlin and see what happens?  (you probably have to install kotlin-cli if you're going through command line).  I'm just curious.

The only other thing I could think of was I'm targeting a mobile device so maybe it's a ARM x86 related issue (like one of dependencies behaving differently).  I'm assuming `argT.parsedType` is not supposed to be `null` when it's going through `for` loop

**Comment by michaeltchuang** [comment]
> created #511 for the err msg thing so we don't forget to fix that but its untested

I tested your change locally and added a quick suggestion if you like it better: https://github.com/algorand/java-algorand-sdk/pull/511/files#r1122634120

**Comment by barnjamin** [comment]
@michaeltchuang with the above change are you able to get a better error message?

**Comment by michaeltchuang** [comment]
@barnjamin it didn't provide too much new information (since I'm able to do breakpoints before it), but it gave me an idea...so today I decided to rewrite my ATC function (in original post) completely into `Java` and call it with with lowercase `boolean` as parameter.  When it hits `MethodCallParams.java` it gets converted to uppercase `Boolean` inside the SDK somehow 😕  (tested against 2.0.0 MavenCentral version) and fails like Kotlin version did.  I don't think this is a Kotlin specific problem since it fails with Java too, but I'll trace further and keep you posted...it's gotta be an issue with type conversion.

**Comment by michaeltchuang** [comment]
@barnjamin So I think I see what's going on.  Your code works in `MethodCallParams.java` because `argT.parsedType` is returning `bool`.  I modified your code to `Method m = new Method("flip_coin(pay,bool)uint64");`  It's missing the `name` and `desc` in `contract.json`

<img width="1073" alt="Screenshot 2023-03-03 at 12 11 00 AM" src="https://user-images.githubusercontent.com/834255/222667542-3cc35a28-d7c1-4234-be31-c9598decdc82.png">

I was using `getMethodByName("flip_coin", contract)` from the docs and `argT.parsedType` isn't set correctly this way as you can see from screenshot below.

<img width="1316" alt="Screenshot 2023-03-03 at 12 12 05 AM" src="https://user-images.githubusercontent.com/834255/222667856-c8380b89-d5a4-46d3-a9d9-4df0a1d88efc.png">

I think the docs syntax approach is probably simpler to understand for new devs so I can try to see if I can update `getMethodByName` function or `Method.java` so all variable fields are set correctly during this ATC use case.

**Comment by michaeltchuang** [comment]
@barnjamin I tested your new `Encoder` version from docs, and it's works on `v2.0.0` (`parsedType` is not `null`)...so I migrated my code to that

`val contract: Contract = Gson().fromJson(contractStr, Contract::class.java)`

to

`val contract: Contract = Encoder.decodeFromJson(contractStr, Contract::class.java)`

<img width="1806" alt="Screenshot 2023-03-23 at 1 55 53 PM" src="https://user-images.githubusercontent.com/834255/227367881-decc8391-4802-406c-af98-aadb84a1efc4.png">

Feel free to close this issue once Inc team decides if Gson case is supposed to be supported or not

**Comment by barnjamin** [comment]
closing now that doc examples are updated to the correct approach. Thanks for testing and sorry for time spent on bad example
