### ISSUE TITLE
`algod/client/model/Transaction` API response model only supports reporting `PaymentTransactionType` transaction info

### ISSUE THREAD

**Issue by EvanJRichard** [algorand/java-algorand-sdk#71]
found by @algonautshant 
The REST model of a `Transaction` returned by a `TransactionInformation` `GET` will only decode Payment fields. It does not support KeyReg fields or any asset fields. So, if you use the java SDK to `GET` information about (for example) an asset transfer transaction, you do not get information such as the asset receiver.

**Comment by algonautshant** [comment]
In case of asset send transaction, since it is not a payment transaction, there will be no PaymentTransactionType. The "to" field is in PaymentTransactionType and not in Transaction. How can one obtain the asset receiver information? This is not possible in Java, and this is part of what this issue is about. I am not understanding how this can be done in go.

**Comment by EvanJRichard** [comment]
More context: the `algod` node potentially reports the following information (`go-algorand/daemon/algod/api/spec/v1/model.go`) - and of the below, Java only supports `PaymentTransactionType`
```
	// This is a list of all supported transactions.
	// To add another one, create a struct with XXXTransactionType and embed it here.
	// To prevent extraneous fields, all must have the "omitempty" tag.

	// Payment contains the additional fields for a payment transaction.
	//
	// required: false
	Payment *PaymentTransactionType `json:"payment,omitempty"`

	// Keyreg contains the additional fields for a keyreg transaction.
	//
	// required: false
	Keyreg *KeyregTransactionType `json:"keyreg,omitempty"`

	// AssetConfig contains the additional fields for an asset config transaction.
	//
	// required: false
	AssetConfig *AssetConfigTransactionType `json:"curcfg,omitempty"`

	// AssetTransfer contains the additional fields for an asset transfer transaction.
	//
	// required: false
	AssetTransfer *AssetTransferTransactionType `json:"curxfer,omitempty"`

	// AssetFreeze contains the additional fields for an asset freeze transaction.
	//
	// required: false
	AssetFreeze *AssetFreezeTransactionType `json:"curfrz,omitempty"`
```

**Comment by ian-algorand** [comment]
fixed with API v2
