### ISSUE TITLE
add the missing PrivateKeyToSeed method to java

### ISSUE THREAD

**Issue by wisthsb1519** [algorand/java-algorand-sdk#95]
add the missing PrivateKeyToSeed method to java that takes a full 64-byte private key and converts it to a 32-byte seed

**Comment by algorotem** [comment]
Hi @wisthsb1519,

Can you please provide more details about the use case?

**Comment by nkavian** [comment]
Most likely the person is saying that we want to backup the `seed` of the account, and requesting you to add a convinence method to make things more obvious. Here is what I'm doing as a workaround which seems tedious to use a 25 word string as an intermediary:

```
        final Account account = new Account();
        final byte[] bytes = Mnemonic.toKey(account.toMnemonic()); <-------
        final String seed = Base64.encodeBase64String(bytes);
```
Versus
```
        final String seed = account.toSeed();
```

Would also be nice to have a string constructor for seed
```
        final String seed = ....;
        final Account account = new Account(seed);
```

**Comment by urajbhandari** [comment]
I have created a PR for this issue: https://github.com/algorand/java-algorand-sdk/pull/231
