### ISSUE TITLE
allow KMD to accept account addresses

### ISSUE THREAD

**Issue by wisthsb1519** [algorand/java-algorand-sdk#96]
for example, `ImportMultisigRequest` takes in a public key which forces you to decode an address

https://github.com/algorand/java-algorand-sdk/blob/aaa4b68142ee7e01d8aae6e03c21e530ca340c00/src/main/java/com/algorand/algosdk/kmd/client/model/ImportMultisigRequest.java#L71

python works nicely where it takes in an msig object to import a multisig account into a kmd wallet
https://github.com/algorand/py-algorand-sdk/blob/b079db660ae92d0dbf24dc04f28eb722711e426f/algosdk/kmd.py#L353

**Comment by winder** [comment]
This wont be addressed until we move the KMD API to the same framework used by the new v2 endpoints and clients. Currently there's no concrete plan to do that.

The code generator used for KMD is not great, so it would be difficult to address this. For the time being you'll need to parse the address:
```
        Address addr = new Address(...);
        Ed25519PublicKey pk = new Ed25519PublicKey(addr.getBytes());
```
